# Generated by Django 2.2.1 on 2019-05-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crush',
            name='solteiro',
            field=models.BooleanField(default=False),
        ),
    ]
